service: backend-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    OTP_TABLE: ${self:service}-otp-${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET, 'emotiox-dev-secret-key-2024'}
    SES_FROM_EMAIL: ${env:SES_FROM_EMAIL}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:4700
        - http://localhost:3000
        - https://app.emotio-x.com
        - https://dev.emotio-x.com
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - Accept
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true
      maxAge: 600 # 10 minutos

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.USERS_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.OTP_TABLE}"
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

functions:
  # Funciones de autenticación
  requestOTP:
    handler: src/handlers/auth.requestOTP
    events:
      - httpApi:
          path: /auth/request-otp
          method: POST

  validateOTP:
    handler: src/handlers/auth.validateOTP
    events:
      - httpApi:
          path: /auth/validate-otp
          method: POST

  logout:
    handler: src/handlers/auth.logout
    events:
      - httpApi:
          path: /auth/logout
          method: POST

  # Funciones de gestión de usuarios
  createUser:
    handler: src/handlers/user.createUser
    events:
      - httpApi:
          path: /users
          method: POST

  getUser:
    handler: src/handlers/user.getUser
    events:
      - httpApi:
          path: /users/me
          method: GET

  updateUser:
    handler: src/handlers/user.updateUser
    events:
      - httpApi:
          path: /users/me
          method: PUT

  deleteUser:
    handler: src/handlers/user.deleteUser
    events:
      - httpApi:
          path: /users/me
          method: DELETE

  # Función para manejar las opciones CORS
  optionsHandler:
    handler: src/handlers/cors.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: OPTIONS

resources:
  Outputs:
    ApiUrl:
      Description: "API Gateway endpoint URL"
      Value: !Join ['', ['https://', !Ref HttpApi, '.execute-api.', !Ref 'AWS::Region', '.amazonaws.com']]
    Endpoints:
      Description: "API Endpoints"
      Value: !Join 
        - ''
        - - '{"requestOTP":{"POST":"/auth/request-otp"},'
          - '"validateOTP":{"POST":"/auth/validate-otp"},'
          - '"logout":{"POST":"/auth/logout"},'
          - '"createUser":{"POST":"/users"},'
          - '"getUser":{"GET":"/users/me"},'
          - '"updateUser":{"PUT":"/users/me"},'
          - '"deleteUser":{"DELETE":"/users/me"}}'

  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OTPTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.OTP_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-export-outputs

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    platform: node
    format: cjs
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['.build/**/*', 'node_modules/**/*']
  exportOutputs:
    fileName: '../frontend/src/config/outputs.json'
    format: json
    indent: 2
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true
    useChildProcesses: true
  tablenames:
    otp: ${self:provider.environment.OTP_TABLE}
    users: ${self:provider.environment.USERS_TABLE} 