name: Deploy public-tests to AWS S3 + CloudFront
on:
  push:
    branches: [main]
    paths: ['public-tests/**']
  pull_request:
    branches: [main]
    paths: ['public-tests/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: public-tests/package-lock.json

      - name: Install dependencies
        run: |
          cd public-tests
          npm ci

      - name: Build application
        run: |
          cd public-tests
          npm run build
        env:
          VITE_BUILD_HASH: ${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync public-tests/dist s3://${{ secrets.PUBLIC_TESTS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PUBLIC_TESTS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
