# Configuración centralizada de endpoints para todos los servicios
# Este archivo se actualiza automáticamente en cada deploy

environments:
  development:
    backend:
      base_url: "https://api-dev.emotioxv2.com"
      region: "us-east-1"
      stage: "dev"
    frontend:
      base_url: "https://admin-dev.emotioxv2.com"
    public_tests:
      base_url: "https://tests-dev.emotioxv2.com"
    s3:
      bucket: "emotioxv2-uploads-dev"
      region: "us-east-1"
    cloudfront:
      distribution_id: "E1234567890DEV"
      domain: "d1234567890dev.cloudfront.net"

  staging:
    backend:
      base_url: "https://api-staging.emotioxv2.com"
      region: "us-east-1"
      stage: "staging"
    frontend:
      base_url: "https://admin-staging.emotioxv2.com"
    public_tests:
      base_url: "https://tests-staging.emotioxv2.com"
    s3:
      bucket: "emotioxv2-uploads-staging"
      region: "us-east-1"
    cloudfront:
      distribution_id: "E1234567890STAGING"
      domain: "d1234567890staging.cloudfront.net"

  production:
    backend:
      base_url: "https://api.emotioxv2.com"
      region: "us-east-1"
      stage: "prod"
    frontend:
      base_url: "https://admin.emotioxv2.com"
    public_tests:
      base_url: "https://tests.emotioxv2.com"
    s3:
      bucket: "emotioxv2-uploads-prod"
      region: "us-east-1"
    cloudfront:
      distribution_id: "E1234567890PROD"
      domain: "d1234567890prod.cloudfront.net"

# Endpoints específicos por servicio
endpoints:
  backend:
    auth: "/auth"
    research: "/research"
    participants: "/participants"
    responses: "/responses"
    forms: "/forms"
    educational_content: "/educational-content"
    eye_tracking: "/eye-tracking"
    smart_voc: "/smart-voc"
    cognitive_tasks: "/cognitive-tasks"
    module_responses: "/module-responses"
    websocket: "/ws"
  
  frontend:
    dashboard: "/dashboard"
    research: "/research"
    participants: "/participants"
    results: "/results"
    settings: "/settings"
  
  public_tests:
    test: "/test"
    participant: "/participant"
    results: "/results"

# Configuración de AWS
aws:
  regions:
    primary: "us-east-1"
    secondary: "us-west-2"
  
  services:
    lambda:
      timeout: 30
      memory: 512
      runtime: "nodejs18.x"
    
    api_gateway:
      timeout: 30
      throttling:
        rate_limit: 1000
        burst_limit: 2000
    
    dynamodb:
      billing_mode: "PAY_PER_REQUEST"
      point_in_time_recovery: true
    
    s3:
      versioning: true
      encryption: "AES256"
      lifecycle:
        transition_to_ia: 30
        transition_to_glacier: 90
    
    cloudfront:
      cache_behavior:
        default_ttl: 86400
        max_ttl: 31536000
        min_ttl: 0
