# Bucket S3 para almacenamiento - Comentado porque ya existe y no puede ser gestionado por CloudFormation
# StorageBucket:
#   Type: AWS::S3::Bucket
#   Properties:
#     BucketName: ${self:custom.s3BucketName}
#     CorsConfiguration:
#       CorsRules:
#         - AllowedHeaders:
#             - '*'
#           AllowedMethods:
#             - GET
#             - PUT
#             - POST
#             - DELETE
#             - HEAD
#           AllowedOrigins:
#             - 'http://localhost:3000'        # Frontend desarrollo
#             - 'http://localhost:4700'        # Public-tests desarrollo
#             - 'http://localhost:5173'        # Vite alternativo
#             - 'http://localhost:5174'        # Vite alternativo
#             - 'https://d2s9nr0bm47yl1.cloudfront.net'  # Frontend CloudFront
#             - 'https://d2zt8ia21te5mv.cloudfront.net'  # Public-tests CloudFront
#             - 'http://54.90.132.233:3000'    # Frontend EC2
#             - '*'                            # Fallback para desarrollo
#           MaxAge: 3000
#     PublicAccessBlockConfiguration:
#       BlockPublicAcls: false
#       BlockPublicPolicy: false
#       IgnorePublicAcls: false
#       RestrictPublicBuckets: false

# Tabla de usuarios (creada condicionalmente)
UsersTable:
  Type: AWS::DynamoDB::Table
  Condition: CreateUsersTable
  Properties:
    TableName: ${self:provider.environment.USER_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb
# 
# Tabla principal DynamoDB (comentada porque ya existe)
# # DynamoDBTable:
#   Type: AWS::DynamoDB::Table
#   Properties:
#     TableName: ${self:provider.environment.DYNAMODB_TABLE}
#     BillingMode: PAY_PER_REQUEST
#     AttributeDefinitions:
#       - AttributeName: id
#         AttributeType: S
#       - AttributeName: sk
#         AttributeType: S
#       - AttributeName: userId
#         AttributeType: S
#       - AttributeName: researchId
#         AttributeType: S
#       - AttributeName: EntityType
#         AttributeType: S
#     KeySchema:
#       - AttributeName: id
#         KeyType: HASH
#       - AttributeName: sk
#         KeyType: RANGE
#     GlobalSecondaryIndexes:
#       - IndexName: userId-index
#         KeySchema:
#           - AttributeName: userId
#             KeyType: HASH
#         Projection:
#           ProjectionType: ALL
# 
#       - IndexName: researchId-index
#         KeySchema:
#           - AttributeName: researchId
#             KeyType: HASH
#         Projection:
#           ProjectionType: ALL
# 
#       - IndexName: EntityTypeSkIndex
#         KeySchema:
#           - AttributeName: EntityType
#             KeyType: HASH
#           - AttributeName: sk
#             KeyType: RANGE
#         Projection:
#           ProjectionType: ALL
# 
#     PointInTimeRecoverySpecification:
#       PointInTimeRecoveryEnabled: true
#     SSESpecification:
#       SSEEnabled: true
#       SSEType: KMS
#       KMSMasterKeyId: alias/aws/dynamodb
# 
# Tabla EyeTracking Recruit Config
EyeTrackingRecruitConfigTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.EYETRACKING_RECRUIT_CONFIG_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# Tabla EyeTracking Recruit Participant
EyeTrackingRecruitParticipantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.EYETRACKING_RECRUIT_PARTICIPANT_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      - AttributeName: GSI2PK
        AttributeType: S
      - AttributeName: GSI2SK
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: GSI2
        KeySchema:
          - AttributeName: GSI2PK
            KeyType: HASH
          - AttributeName: GSI2SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# Tabla Recruitment Link
RecruitmentLinkTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.RECRUITMENT_LINK_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      - AttributeName: token
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: TokenIndex
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# Tabla de participantes
ParticipantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.PARTICIPANT_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES

# Tabla para las Respuestas de Módulos
ModuleResponsesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.MODULE_RESPONSES_TABLE} # Usa la variable de entorno
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id            # Clave primaria de la tabla (ej. UUID para el documento de respuestas del participante)
        AttributeType: S
      - AttributeName: researchId    # Para el GSI ResearchParticipantIndex y ResearchIndex (Clave de Partición)
        AttributeType: S
      - AttributeName: participantId # Para el GSI ResearchParticipantIndex (Clave de Ordenación)
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ResearchParticipantIndex # El índice que estás usando en findByResearchAndParticipant
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
          - AttributeName: participantId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL # Proyecta todos los atributos al índice
      - IndexName: ResearchIndex # El índice que usas en getResponsesByResearch
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# Permite acceso público de solo lectura a todos los archivos del bucket
# COMENTADO: No se puede aplicar política sin actualizar primero las configuraciones del bucket existente
# S3PublicReadPolicy:
#   Type: AWS::S3::BucketPolicy
#   Properties:
#     Bucket: ${self:custom.s3BucketName}
#     PolicyDocument:
#       Version: "2012-10-17"
#       Statement:
#         - Sid: AllowPublicReadForAllFiles
#           Effect: Allow
#           Principal: "*"
#           Action: "s3:GetObject"
#           Resource: "arn:aws:s3:::${self:custom.s3BucketName}/*"

# Tabla para Location Tracking
LocationTrackingTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.LOCATION_TRACKING_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: researchId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ResearchIdIndex
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# Tabla para Quota Records
QuotaRecordsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.QUOTA_RECORDS_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: researchId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ResearchIdIndex
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
      SSEType: KMS
      KMSMasterKeyId: alias/aws/dynamodb

# --- Fin de las definiciones de Recursos ---
