# Bucket S3 para almacenamiento
StorageBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:provider.environment.S3_BUCKET_NAME}
    CorsConfiguration:
      CorsRules:
        - AllowedHeaders:
            - '*'
          AllowedMethods:
            - GET
            - PUT
            - POST
            - DELETE
            - HEAD
          AllowedOrigins:
            - 'http://localhost:4700'
            - 'https://your-production-frontend-domain.com'
          MaxAge: 3000
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false

# Tabla de usuarios
UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.USER_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Tabla principal DynamoDB
DynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.DYNAMODB_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      - AttributeName: researchId
        AttributeType: S
      - AttributeName: EntityType
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: userId-index
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        Projection:
          ProjectionType: ALL

      - IndexName: researchId-index
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
        Projection:
          ProjectionType: ALL

      - IndexName: EntityTypeSkIndex
        KeySchema:
          - AttributeName: EntityType
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        Projection:
          ProjectionType: ALL

    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Tabla EyeTracking Recruit Config
EyeTrackingRecruitConfigTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.EYETRACKING_RECRUIT_CONFIG_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Tabla EyeTracking Recruit Participant
EyeTrackingRecruitParticipantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.EYETRACKING_RECRUIT_PARTICIPANT_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      - AttributeName: GSI2PK
        AttributeType: S
      - AttributeName: GSI2SK
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: GSI2
        KeySchema:
          - AttributeName: GSI2PK
            KeyType: HASH
          - AttributeName: GSI2SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Tabla Recruitment Link
RecruitmentLinkTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.RECRUITMENT_LINK_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      - AttributeName: token
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
          - AttributeName: GSI1PK
            KeyType: HASH
          - AttributeName: GSI1SK
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: TokenIndex
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Tabla de participantes
ParticipantTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.PARTICIPANT_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: email
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: EmailIndex
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES

# Tabla para las Respuestas de Módulos
ModuleResponsesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.environment.MODULE_RESPONSES_TABLE} # Usa la variable de entorno
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id            # Clave primaria de la tabla (ej. UUID para el documento de respuestas del participante)
        AttributeType: S
      - AttributeName: researchId    # Para el GSI ResearchParticipantIndex y ResearchIndex (Clave de Partición)
        AttributeType: S
      - AttributeName: participantId # Para el GSI ResearchParticipantIndex (Clave de Ordenación)
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: ResearchParticipantIndex # El índice que estás usando en findByResearchAndParticipant
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
          - AttributeName: participantId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL # Proyecta todos los atributos al índice
      - IndexName: ResearchIndex # El índice que usas en getResponsesByResearch
        KeySchema:
          - AttributeName: researchId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    SSESpecification:
      SSEEnabled: true

# Permite acceso público de solo lectura a los archivos bajo cognitive-task-files/
S3PublicReadPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref StorageBucket
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Sid: AllowPublicReadForCognitiveTaskFiles
          Effect: Allow
          Principal: "*"
          Action: "s3:GetObject"
          Resource: !Sub "${StorageBucket.Arn}/cognitive-task-files/*"

# --- Fin de las definiciones de Recursos ---
# La sección Outputs se movió de nuevo a serverless.yml
