service: emotioxv2-backend

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-export-outputs
  - serverless-plugin-export-endpoints

# Configuración de esbuild para compilación TypeScript optimizada
custom:
  # Nombres dinámicos de recursos (se crean si no existen)
  tableName: ${opt:existing-table, '${self:service}-researches-${self:provider.stage}'} # Tabla para Investigaciones
  usersTableName: ${opt:existing-users-table, '${self:service}-users-${self:provider.stage}'} # Tabla para Usuarios
  s3BucketName: ${opt:existing-bucket, 'emotioxv2-uploads-${self:provider.stage}'} # Bucket S3 dinámico (usa el que ya existe)
  
  # Condiciones para crear recursos solo si no se especifican existentes
  createNewBucket: ${env:CREATE_NEW_BUCKET, 'true'}
  createNewTables: ${env:CREATE_NEW_TABLES, 'true'}
  eyeTrackingRecruitConfigTable: ${self:service}-eye-tracking-recruit-config-${self:provider.stage}
  eyeTrackingRecruitParticipantTable: ${self:service}-eye-tracking-recruit-participant-${self:provider.stage}
  recruitmentLinkTable: ${self:service}-recruitment-link-${self:provider.stage}

  # Configuración para entorno de desarrollo
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    websocketPort: 3001
    noPrependStageInUrl: true
    allowCache: true

  # Exportar endpoints para frontend
  exportOutputs:
    include:
      - HttpApiUrl
      - WebsocketApiUrl
    output:
      file: ./endpoints-output.json

  exportEndpoints:
    fileName: ./endpoints.json
    include:
      - 'http'
      - 'httpApi'
      - 'websocket'

  # Variables de entorno dinámicas
  stages:
    dev:
      apiGatewayCors: '*'
    prod:
      apiGatewayCors: ${env:ALLOWED_ORIGIN, '*'}

  # Configuración de esbuild
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 30
  logRetentionInDays: 7

  stackTags:
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}

  apiGateway:
    shouldStartNameWithService: true
    # Mantener la configuración de caché comentada por ahora
    # cacheClusterEnabled: true
    # cacheClusterSize: '0.5'
    # cacheDataEncrypted: true
    # cacheTtlInSeconds: 300

  environment: ${file(./environment-variables.yml)}
  iam: ${file(./iam-permissions.yml)}

functions: ${file(./function-definitions.yml)}

resources:
  Conditions: ${file(./conditions.yml)}
  Resources: ${file(./resources.yml)}
  Outputs: ${file(./outputs.yml)}
