name: Configure Amplify Environment Variables

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths:
      - 'frontend/src/config/**'
      - 'frontend/AMPLIFY_ENV_VARS.md'

jobs:
  configure-amplify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure Amplify Environment Variables
      run: |
        # Variables de entorno para EmotioXV2
        APP_ID="d1718q1uyn5ffx"

        # Crear archivo JSON con las variables
        cat > amplify-env-vars.json << EOF
        {
          "environmentVariables": {
            "NEXT_PUBLIC_API_URL": "https://d5x2q3te3j.execute-api.us-east-1.amazonaws.com/dev",
            "NEXT_PUBLIC_API_BASE_URL": "https://d5x2q3te3j.execute-api.us-east-1.amazonaws.com/dev",
            "NEXT_PUBLIC_WS_URL": "wss://d5x2q3te3j.execute-api.us-east-1.amazonaws.com/dev",
            "NEXT_PUBLIC_PUBLIC_TESTS_URL": "https://main.dgsabzeqh9eea.amplifyapp.com"
          }
        }
        EOF

        # Actualizar la app de Amplify
        aws amplify update-app \
          --app-id $APP_ID \
          --cli-input-json file://amplify-env-vars.json \
          --region us-east-1

        echo "✅ Variables de entorno configuradas en Amplify"

    - name: Trigger Amplify Build
      run: |
        APP_ID="d1718q1uyn5ffx"
        BRANCH_NAME="main"

        aws amplify start-job \
          --app-id $APP_ID \
          --branch-name $BRANCH_NAME \
          --job-type RELEASE \
          --region us-east-1

        echo "✅ Build de Amplify iniciado"
