name: Deploy to AWS Amplify

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - 'shared/**'
      - '.github/workflows/deploy-amplify.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'shared/**'

env:
  NODE_VERSION: '18'
  AWS_REGION: 'us-east-1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          package-lock.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install root dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint frontend code
      run: |
        cd frontend
        npm run lint:check

    - name: Verify API configuration
      run: |
        cd frontend
        npm run verify:api

    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        NODE_ENV: production

    - name: Deploy to Amplify (Main Branch)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        aws amplify start-job \
          --app-id ${{ secrets.AMPLIFY_APP_ID }} \
          --branch-name main \
          --job-type RELEASE
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to Amplify (Develop Branch)
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: |
        aws amplify start-job \
          --app-id ${{ secrets.AMPLIFY_APP_ID }} \
          --branch-name develop \
          --job-type RELEASE
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get deployment status
      if: github.event_name == 'push'
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        JOB_ID=$(aws amplify list-jobs --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name $BRANCH_NAME --max-items 1 --query 'jobSummaries[0].jobId' --output text)
        echo "Deployment Job ID: $JOB_ID"
        echo "Monitor deployment at: https://console.aws.amazon.com/amplify/home?region=${{ env.AWS_REGION }}#/${{ secrets.AMPLIFY_APP_ID }}/$BRANCH_NAME/$JOB_ID"

    - name: Notify deployment result
      if: always() && github.event_name == 'push'
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
          exit 1
        fi
